### ISSUE TITLE
Where is neural_predictors.py?

### ISSUE THREAD

**Issue by orxai** [google-deepmind/neural_networks_solomonoff_induction#2]
Hi, Sorry, Am I missing something?
https://github.com/google-deepmind/neural_networks_solomonoff_induction/blob/b42a7028305bef0757e769df0754e54e164f7f01/train.py#L49

**Comment by fazega** [comment]
Fixed in latest [merged commit](https://github.com/google-deepmind/neural_networks_solomonoff_induction/commit/e7fe6d0f4f9189e73b65eb47b682e62ed4d87162).
