### ISSUE TITLE
What is meant by "interesting" sequences in the paper ?

### ISSUE THREAD

**Issue by alxndrTL** [google-deepmind/neural_networks_solomonoff_induction#5]
Hello,

This question is not directly related to this repo but rather to the paper where it is stated there that the sampling probability distribution Q was trained to have a better rate of interesting sequences compared to the uniform program sampling.

I wonder what is exactly meant by "interesting" ? It is some kind of manually encoded check that verifies if the program output is just the same symbol repeated over and over ? Or is it more complex ?

Here are a bunch of sampled program outputs (1 row = 1 output, blue is padding) :
![Capture d’écran du 2024-02-17 22-36-55](https://github.com/google-deepmind/neural_networks_solomonoff_induction/assets/22843596/03b7000f-5cd6-4604-89e7-29077029aff4)

For example, row 50 would pass the cut but 60 is considered not interesting ?

Sorry if this is not related to the code, thank you in advance!

**Comment by Metaxal** [comment]
Hi, thanks for your interest in Table 3! 

Most of Table 3 can be obtained by training the Markov model from shortened programs, as explained in Appendix E.3.
The corresponding code for shortening programs is [here](https://github.com/google-deepmind/neural_networks_solomonoff_induction/blob/main/data/utms.py#L233).

Additionally, as said in the caption of Table 3, 'boring' output sequences are filtered out ('interesting' = not 'boring'). 

A sequence is boring if its shortened program is longer than a threshold (program is too complex; we used a threshold of 100), or if its output isn't of maximum length (program is too slow).

A sequence is also boring if it is too repetitive. Here's a function that counts the number of repetitions in a sequence for a given delay between symbols:
```python
def repeating_count(output, delay):
  count = 0 # number of equal elements
  for i in range(delay + 1, len(output)):
    if output[i] == output[i-delay]: count += 1
  return count
```
Then we search for the delay that maximizes the repeating count. If this max repeating count is larger than 70% of the sequence length, the sequence is boring.

So for example the sequence "abababab..." is boring, while the sequence enumerating the binary numbers is not boring.

I hope this helps.

**Comment by alxndrTL** [comment]
Thank you for your detailed response, this is precisely what I was wondering!
